<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>866a1731-8597-4038-9d2d-94de62505be4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\" />
    <Folder Include="Mappings\" />
    <Folder Include="Middlewares\" />
    <Folder Include="_Common\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Analitycs.IOC\Analitycs.IOC.csproj" />
    <ProjectReference Include="..\Analytics.Application\Analytics.Application.csproj" />
  </ItemGroup>

</Project>
