apiVersion: v1
kind: Service
metadata:
  name: properties-api
spec:
  type: NodePort
  selector:
    app: properties-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30081
