services:
  analytics:
    build:
      context: ../src/Analytics
      dockerfile: Analytics.API/Dockerfile
    container_name: analytics
    depends_on:
      - redis
    ports:
      - "5002:8081"
    environment:
      - Redis__ConnectionString=redis:6379
      - Services__IngressApi=http://ingress:8080/api/Health/status
      - Serilog__MinimumLevel=Information

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped