services:
  analytics:
    build:
      context: ../src/Analytics
      dockerfile: Analytics.API/Dockerfile
    container_name: analytics
    depends_on:
      - redis
    ports:
      - "5002:8080"
    env_file:
      - .env
    environment:
      - Redis__ConnectionString=redis:6379
      - Services__IngressApi=http://ingress:8080/api/
      - Keycloak__TokenUrl=http://keycloak:8080/realms/RuralTech/protocol/openid-connect/token
      - Keycloak__ClientId=ruraltech-services
      - Keycloak__ClientSecret=${KEYCLOAK_CLIENT_SECRET}
      - Keycloak__GrantType=client_credentials
      - Serilog__MinimumLevel=Information

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped