services:
  analytics:
    build:
      context: ../src/Analytics
      dockerfile: Analytics.API/Dockerfile
    container_name: analytics
    depends_on:
      - redis
    ports:
      - "5002:8081"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
