services:
  # Microsserviço de Properties
  properties-api:
    image: rural-monitor-properties
    build:
      context: ../src/Properties
      dockerfile: Dockerfile
    container_name: properties-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://admin:adminpassmongo@mongodb-db:27017
      - MongoDbSettings__DatabaseName=properties_db
    ports:
      - "8081:8080" 
    depends_on:
      - mongodb-db

  mongodb-db:
    image: mongo:latest
    container_name: mongodb-db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassmongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: